language: android
android:

  before_install:
    - y | sdkmanager

  components:
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - tools

    - build-tools-26.0.1
    - android-26
     # Support library
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository

jdk:
  # Jdk version used by your project
  - oraclejdk8

script:
  - ./gradlew build connectedCheck
  - ./gradlew test