language: android
android:

  components:
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - tools
    - build-tools-26.0.1
    - android-26
     # Support library
    - extra-android-support
    - extra-android-m2repository

  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

jdk:
  # Jdk version used by your project
  - oraclejdk8

script:
  - ./gradlew build connectedCheck
  - ./gradlew test